apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: hatespeech
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/auth/metrics"
    prometheus.io/port: "8000"
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
